[versions]
springboot = "3.5.4"
androidx-lifecycle = "2.9.0"
kotlinx-coroutines = "1.10.2"
agp = "8.1.1"
javalin = '6.1.3'
kotlin = "2.2.20"
composeHotReload = "1.0.0-beta08"
composeMultiplatform = "1.9.0"
hutool = "5.8.39"
commonmark = "0.21.0"
ideaPluginDev = "2.6.0"
opentest4j = "1.3.0"
junit = "4.13.2"
changelog = "2.2.1"
ideaC = "2024.3.2"
[libraries]
slf4jApi="org.slf4j:slf4j-api:2.0.17"

jakartarServletApi='jakarta.servlet:jakarta.servlet-api:6.1.0'
springDependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "springboot" }
protobufJava = "com.google.protobuf:protobuf-java:4.31.1"
# -------------------------------my projects start------------------------
mySpringApiVersioning = "dev.yzq.layla:spring-api-versioning:1.0.0"
myLaylaSpringbootStarter = "dev.yzq.layla:layla-spring-boot-starter:1.0.0"
myLaylaUtil = "dev.yzq.layla:layla-util:1.0.0"
myLaylaBom = "dev.yzq.layla:layla-bom:1.0.0"
# -------------------------------my projects end------------------------
snakeYaml="org.yaml:snakeyaml:2.4"
gradleTooling = "org.gradle:gradle-tooling-api:8.14"
kspApi = 'com.google.devtools.ksp:symbol-processing-api:2.2.0-2.0.2'
junitBom = "org.junit:junit-bom:5.13.4"# before value => org.junit:junit-bom:5.13.0
junitJupiter = { module = "org.junit.jupiter:junit-jupiter" }
junitLauncher = { module = "org.junit.platform:junit-platform-launcher" }
junit4 = { group = "junit", name = "junit", version.ref = "junit" }
# compose desktop

androidx-lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
kotlinx-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
composeNavigation = "org.jetbrains.androidx.navigation:navigation-compose:2.9.0-beta03"
kotlinTime = "org.jetbrains.kotlinx:kotlinx-datetime:0.6.0"
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-testJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
# utils
## network
okhttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version = "4.+" }
okhttp3-logging = "com.squareup.okhttp3:logging-interceptor:5.0.0-alpha.16"# before value => com.squareup.okhttp3:logging-interceptor:4.+
retrofit = "com.squareup.retrofit2:retrofit:3.0.0"# before value => com.squareup.retrofit2:retrofit:2.9.0
retrofit-gson = "com.squareup.retrofit2:converter-gson:3.0.0"# before value => com.squareup.retrofit2:converter-gson:2.9.0
mockwebserver = "com.squareup.okhttp3:mockwebserver:5.0.0-alpha.16"# before value => com.squareup.okhttp3:mockwebserver:4.10.0
okio = "com.squareup.okio:okio:3.12.0"# before value => com.squareup.okio:okio:3.5.0
netAwesome = "com.github.liangjingkanji:Net:3.7.0" # before value => com.github.liangjingkanji:Net:3.6.1
asyncHttpclient = "org.asynchttpclient:async-http-client:3.0.2"
# apache commons
apiVersion = "com.github.lkqm:spring-api-versioning:1.4.0" # before value => com.github.lkqm:spring-api-versioning:1.4.0
commonsIo = "commons-io:commons-io:2.19.0"# before value => commons-io:commons-io:2.15.1
commonsLang3 = "org.apache.commons:commons-lang3:3.18.0"# before value => org.apache.commons:commons-lang3:3.14.0
commonsText = "org.apache.commons:commons-text:1.13.1"# before value => org.apache.commons:commons-text:1.11.0
commonsCollections = "org.apache.commons:commons-collections4:4.5.0"# before value => org.apache.commons:commons-collections4:4.4
commonsCodec = "commons-codec:commons-codec:1.18.0"# before value => commons-codec:commons-codec:1.16.0
commonsValidator = 'commons-validator:commons-validator:1.9.0'
# // https://mvnrepository.com/artifact/commons-net/commons-net
commonsNet = "commons-net:commons-net:3.11.1"# before value => commons-net:commons-net:3.10.0
commonsFileupload = "commons-fileupload:commons-fileupload:1.6.0"# before value => commons-fileupload:commons-fileupload:1.5
commonsFileupload2 = "org.apache.commons:commons-fileupload2:2.0.0-M4"# before value => org.apache.commons:commons-fileupload2:2.0.0-M2
commonsFileuploadJakarta = "org.apache.commons:commons-fileupload2-jakarta-servlet6:2.0.0-M4"# before value => org.apache.commons:commons-fileupload2-jakarta-servlet6:2.0.0-M2
commonsMail = "org.apache.commons:commons-email:1.6.0"
commonsPool = "org.apache.commons:commons-pool2:2.12.1"# before value => org.apache.commons:commons-pool2:2.12.0
#下面包含jakarta.mail包
jakartaEmail = "org.eclipse.angus:jakarta.mail:2.0.3"
#下面不包含jakarta.mail包,其他的一样(推荐使用)
augusMail = "org.eclipse.angus:angus-mail:2.0.3"
fakedata = "net.datafaker:datafaker:2.4.3"# before value => net.datafaker:datafaker:2.0.2
httpclient4 = "org.apache.httpcomponents:httpclient:4.5.14"
httpclient5 = "org.apache.httpcomponents.client5:httpclient5:5.5"
httpclient5Fluent = "org.apache.httpcomponents.client5:httpclient5-fluent:5.5"
guava = "com.google.guava:guava:33.4.8-jre"
thumbnailator = "net.coobird:thumbnailator:0.4.20"
jsoup = "org.jsoup:jsoup:1.21.1"# before value => org.jsoup:jsoup:1.16.1
poiOoxml = "org.apache.poi:poi-ooxml:5.4.1"# before value => org.apache.poi:poi-ooxml:5.2.5
#// https://mvnrepository.com/artifact/com.alibaba/easyexcel
easyexcel = "com.alibaba:easyexcel:4.0.3"# before value => com.alibaba:easyexcel:4.0.1
# https://mvnrepository.com/artifact/com.freewayso/image-combiner
imageCombiner="com.freewayso:image-combiner:2.6.9"
#dromara
#// https://mvnrepository.com/artifact/cn.hutool/hutool-all
hutool = { module = 'cn.hutool:hutool-all', version.ref = 'hutool' }
hutoolBom = { module = "cn.hutool:hutool-bom", version.ref = 'hutool' }
satokenBoot = "cn.dev33:sa-token-spring-boot-starter:1.44.0"
satokenBoot3 = "cn.dev33:sa-token-spring-boot3-starter:1.44.0"
satokenRedis = "cn.dev33:sa-token-redis-jackson:1.44.0"
forestBoot = "com.dtflys.forest:forest-spring-boot-starter:1.7.1"# before value => com.dtflys.forest:forest-spring-boot-starter:1.5.33
xfileStoreBoot = "org.dromara.x-file-storage:x-file-storage-spring:2.2.1"# before value => org.dromara.x-file-storage:x-file-storage-spring:2.0.0
javaassist = "org.javassist:javassist:3.30.2-GA"
lombokModule = { module = "org.projectlombok:lombok", version = "1.18.38" }
mysql = "com.mysql:mysql-connector-j:9.3.0"# before value => com.mysql:mysql-connector-j:8.4.0
springdoc = "org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.6"# before value => org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.9
springdoc1 = "org.springdoc:springdoc-openapi-ui:1.8.0"
knife4j = "com.github.xiaoymin:knife4j-openapi3-jakarta-spring-boot-starter:4.5.0"# before value => com.github.xiaoymin:knife4j-openapi3-jakarta-spring-boot-starter:4.4.0
springDevtools = { module = "org.springframework.boot:spring-boot-devtools" }
## aop
aspectjTools = "org.aspectj:aspectjtools:1.9.24"# before value => org.aspectj:aspectjtools:1.9.20
#// https://mvnrepository.com/artifact/org.aspectj/aspectjrt
aspectjrt = "org.aspectj:aspectjrt:1.9.24"# before value => org.aspectj:aspectjrt:1.9.20
slf4jSimple = "org.slf4j:slf4j-simple:2.0.17"# before value => org.slf4j:slf4j-simple:2.0.13

logback = "ch.qos.logback:logback-classic:1.5.18"# before value => ch.qos.logback:logback-classic:1.5.6
# json
gson = "com.google.code.gson:gson:latest.release"
# https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind
jackson = "com.fasterxml.jackson.core:jackson-databind:2.18.4"# before value => com.fasterxml.jackson.core:jackson-databind:2.17.1
fastjson = "com.alibaba.fastjson2:fastjson2:2.0.57.android8"# before value => com.alibaba.fastjson2:fastjson2:2.0.51

rxjava3 = "io.reactivex.rxjava3:rxjava:3.1.10"# before value => io.reactivex.rxjava3:rxjava:3.1.8
mybatis3 = "org.mybatis:mybatis:3.5.19"# before value => org.mybatis:mybatis:3.5.15
pageHelper = "com.github.pagehelper:pagehelper:6.1.1"# before value => com.github.pagehelper:pagehelper:6.1.0
mybatisPlusBoot2 = "com.baomidou:mybatis-plus-boot-starter:3.5.7"# before value => com.baomidou:mybatis-plus-boot-starter:3.5.12
mybatisPlusBoot = "com.baomidou:mybatis-plus-spring-boot3-starter:3.5.7"# before value => com.baomidou:mybatis-plus-spring-boot3-starter:3.5.12
mybatisFlexBoot3 = "com.mybatis-flex:mybatis-flex-spring-boot3-starter:1.10.8"# before value => com.mybatis-flex:mybatis-flex-spring-boot3-starter:1.10.9
mybatisFlexBoot = "com.mybatis-flex:mybatis-flex-spring-boot-starter:1.10.8"# before value => com.mybatis-flex:mybatis-flex-spring-boot-starter:1.10.9
mybatisFlexAnno = "com.mybatis-flex:mybatis-flex-processor:1.10.8"# before value => com.mybatis-flex:mybatis-flex-processor:1.10.9
hikra = "com.zaxxer:HikariCP:6.3.0"# before value => com.zaxxer:HikariCP:5.1.0
#// https://mvnrepository.com/artifact/com.alibaba/druid-spring-boot-starter
druidSpringboot = "com.alibaba:druid-spring-boot-starter:1.2.25"
druidSpringboot3 = "com.alibaba:druid-spring-boot-3-starter:1.2.25"
mapstruct = "org.mapstruct:mapstruct:1.6.3"# before value => org.mapstruct:mapstruct:1.5.5.Final
# https://mvnrepository.com/artifact/org.mapstruct/mapstruct-processor
mapstructAnno = "org.mapstruct:mapstruct-processor:1.6.3"# before value => org.mapstruct:mapstruct-processor:1.5.5.Final
javaJwt = "com.auth0:java-jwt:4.5.0"

# https://mvnrepository.com/artifact/io.jsonwebtoken/jjwt-api
jjwtApi = "io.jsonwebtoken:jjwt-api:0.12.6"
jjwt = "io.jsonwebtoken:jjwt:0.12.6"

jjwtImpl = 'io.jsonwebtoken:jjwt-impl:0.12.6'
jjwtJackson = 'io.jsonwebtoken:jjwt-jackson:0.12.6'
# https://mvnrepository.com/artifact/org.apache.shiro/shiro-spring-boot-web-starter
shiroBoot = "org.apache.shiro:shiro-spring-boot-web-starter:2.0.4"
shiroBoot1Module = { module = "org.apache.shiro:shiro-spring-boot-web-starter" }
problemBoot2 = { module = "org.zalando:problem-spring-web", version = "0.27.0" }
problemBoot3 = { module = "org.zalando:problem-spring-web", version = "0.29.1" }
pebble="io.pebbletemplates:pebble-spring-boot-starter:3.2.0"
#// JSON序列化库, 首选推荐使用
kotlinxSeriJson = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.9.0"# before value => org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.3
#// protobuf序列化
kotlinSeriproto = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf:1.9.0"# before value => org.jetbrains.kotlinx:kotlinx-serialization-protobuf:1.6.3
#// JSON序列化库, 强校验, JSON字段缺失会导致解析异常, 故不推荐
moshi = "com.squareup.moshi:moshi-kotlin:1.15.2"# before value => com.squareup.moshi:moshi-kotlin:1.14.0
kotlinReflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
kotlinStdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutinescore = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2"# before value => org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4
kotlinx-coroutines-android = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.2"# before value => org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4
# rxjava
rxjava2 = "io.reactivex.rxjava2:rxjava:2.2.21"
# picture
nettyAll = "io.netty:netty-all:4.2.1.Final"# before value => io.netty:netty-all:4.1.105.Final
jedis = "redis.clients:jedis:6.0.0"# before value => redis.clients:jedis:4.3.1
commonMark = { module = "org.commonmark:commonmark", version.ref = "commonmark" }
commonmarkExtAutolink = { module = "org.commonmark:commonmark-ext-autolink", version.ref = "commonmark" }
commonmarkFgmTable = { module = "org.commonmark:commonmark-ext-gfm-tables", version.ref = "commonmark" }
commonmarkStrikethrough = { module = "org.commonmark:commonmark-ext-gfm-strikethrough", version.ref = "commonmark" }
commonmarkHeadingAnchor = { module = "org.commonmark:commonmark-ext-heading-anchor", version.ref = "commonmark" }
commonmarkImageAttr = { module = "org.commonmark:commonmark-ext-image-attributes", version.ref = "commonmark" }
commonmarkIns = { module = "org.commonmark:commonmark-ext-ins", version.ref = "commonmark" }
commonmarkTaskListItem = { module = "org.commonmark:commonmark-ext-task-list-items", version.ref = "commonmark" }
commonmarkParent = { module = "org.commonmark:commonmark-parent", version.ref = "commonmark" }
## javalin
javalin = { module = 'io.javalin:javalin', version.ref = 'javalin' }
javalinApiProcessor = { module = "io.javalin.community.openapi:openapi-annotation-processor", version.ref = 'javalin' }
javalinApiPlugin = { module = "io.javalin.community.openapi:javalin-openapi-plugin", version.ref = 'javalin' }
javalinSwaggerPlugin = { module = "io.javalin.community.openapi:javalin-swagger-plugin", version.ref = 'javalin' }
opentest4j = { group = "org.opentest4j", name = "opentest4j", version.ref = "opentest4j" }

[plugins]
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "ideaPluginDev" }
springDependency = { id = "io.spring.dependency-management", version = "1.1.7" }

springboot2 = { id = "org.springframework.boot", version = "2.7.18" }
springboot = { id = "org.springframework.boot", version.ref = "springboot" }
springPlugin = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
shadowJar = { id = "com.gradleup.shadow", version = "9.1.0" }
ksp = { id = "com.google.devtools.ksp", version = "2.2.0-2.0.2" }
serial = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
[bundles]
commons = [
    "commonsIo",
    "commonsCollections",
    "commonsLang3",
    "commonsText",
    "commonsNet",
    "commonsValidator",
    "commonsCodec",
    "commonsFileupload2",
    "commonsFileuploadJakarta",
    "commonsPool",
    "fakedata"
]
commonmark = ["commonmarkParent", "commonMark", "commonmarkStrikethrough", "commonmarkExtAutolink", "commonmarkFgmTable", "commonmarkHeadingAnchor", "commonmarkImageAttr", "commonmarkIns", "commonmarkTaskListItem"
]
javalin = ['javalin', 'javalinApiPlugin', 'javalinSwaggerPlugin']
springUtils = ["springdoc"]

utils = ["hutool", "guava", "javaassist", "httpclient5Fluent", "rxjava3"]
