/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot") version "2.7.8"
    id("io.spring.dependency-management") version "1.1.0"
    kotlin("jvm") version "1.8.10"
    kotlin("plugin.spring") version "1.8.10"
}

group = "com.site.blog"
version = "1.0.1"
java.sourceCompatibility = JavaVersion.VERSION_17



dependencies {
    implementation("org.springdoc:springdoc-openapi-ui:1.6.10")
    implementation("com.auth0:java-jwt:4.0.0")
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-actuator")
    implementation("org.springframework.boot:spring-boot-starter-validation")
    implementation("com.dtflys.forest:forest-spring-boot-starter:1.5.25")
    implementation("io.pebbletemplates:pebble-spring-boot-starter:3.1.5")
    implementation("org.springframework.session:spring-session-core:2.7.0")
    implementation("com.baomidou:mybatis-plus-boot-starter:3.5.2")
    implementation("org.projectlombok:lombok:1.18.24")
    annotationProcessor("org.projectlombok:lombok:1.18.24")
    implementation("cn.hutool:hutool-all:5.8.5")
    implementation("org.commonmark:commonmark:0.19.0")
    implementation("org.commonmark:commonmark-ext-gfm-tables:0.19.0")
    implementation("org.springframework.boot:spring-boot-starter-aop")
    implementation("org.springframework.boot:spring-boot-starter-mail")
    implementation("org.springframework.boot:spring-boot-starter-websocket")
    implementation("org.springframework.boot:spring-boot-starter-quartz")
    implementation("org.springframework.boot:spring-boot-configuration-processor")
    implementation("net.sourceforge.nekohtml:nekohtml:1.9.22")
    implementation("net.coobird:thumbnailator:0.4.17")
    implementation("com.alibaba:druid-spring-boot-starter:1.2.11")
    implementation("org.apache.commons:commons-text:1.9")
    runtimeOnly("org.postgresql:postgresql:42.3.6")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
}

group = "com.site.blog"
version = "1.0.1"
description = "my-blog"
java.sourceCompatibility = JavaVersion.VERSION_17



tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
